### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by HowardEdidin** [ms-iot/azure-client-tools#10]
The method names in the DeviceExplorer project did not meet standards. They begin with a lower case character.  `  private async void updateButton_Click(object sender, EventArgs e)`
The first letter should be upper case.

**Comment by gmileka** [comment]
Hi HowardEdidin,

DeviceExplorer is owned by the Azure SDK team. You can open issues in this repo: https://github.com/Azure/azure-iot-sdk-csharp

thanks,
George Mileka
