### ISSUE TITLE
Obsolete code in DeviceExplorer

### ISSUE THREAD

**Issue by HowardEdidin** [ms-iot/azure-client-tools#11]
'RegistryManager.GetDevicesAsync(int)' is obsolete: 'Use CreateQuery("select * from devices", pageSize);'	DeviceExplorer	

Because of this you cannot use an enumeration. The entire function would need to be modified.

**Comment by gmileka** [comment]
Hi HowardEdidin,

Same like the other issue, DeviceExplorer lives here: https://github.com/Azure/azure-iot-sdk-csharp.
Please, feel free to open issues about DeviceExplorer there.

thanks,
George Mileka

**Comment by HowardEdidin** [comment]
Hi George,

The code is correct there.  Shouldn't it be the same in both repositories?
