### ISSUE TITLE
Quick Start: 'Azure Clients' on left pane?

### ISSUE THREAD

**Issue by AlexanderPilhar** [ms-iot/azure-client-tools#12]
Is it possible to follow the [Quick Start](https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/quick-start.md) using a Raspberry Pi 3 Model B?

I know, the RPi doesn't have TPM, so I'm using MSFT TPM Simulator.

Where I'm stuck is [Configure the Device and Start the Device Agent.](https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/quick-start.md#configure-the-device-and-start-the-device-agent) as it seems there is no 'Azure Clients' on left pane.

Tested with 10.0.17744.1001 and 10.0.17763.316.

**Comment by AlexanderPilhar** [comment]
Ah, I found it : )
You first need to go to 'Add tools to workspace' in WDP (located in top left corner hamburger menu) and select 'Azure Client' to be added!

Please, add this information to the 'Quick Start' guide!

**Comment by gmileka** [comment]
Thanks for the report, Alexander. Yes, this makes sense. I've updated the [Quick Start](https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/quick-start.md) page.

We saw another report of the 'missing Azure Clients' tab - and also suggested clearing the browser's cache. Would be interesting to know if this also fixes the problem you're seeing.

**Comment by AlexanderPilhar** [comment]
Thank a lot @gmileka : )
You are right! After clearing the browser's cache WDP looks a little different! Now 'Azure Clients' shows up on the left panel, just like it does shown in the screenshot you posted to 'Quick Start' page. Before clearing the browser's cache 'Azure Clients' was showing up as new tab in 'Device Settings' as well as in 'TPM Configuration'.
