### ISSUE TITLE
AzureDeviceManagementClient.exe Can't load a custom plugin

### ISSUE THREAD

**Issue by v-jiq** [ms-iot/azure-client-tools#16]
I want to load custom plugin  ,So I create a new plugin and put it to Correct position and modify Related configuration file. 
The above operations are completely in accordance with the guidance of this document. 
-- https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/development-scenario/developer-plugin-creation.md .

But when I execute ".\AzureDeviceManagementClient.exe -debug" will can't normally running.
below is log picture. the plugin name is DroneCtlPlugin.dll.
<img width="657" alt="1553058827(1)" src="https://user-images.githubusercontent.com/39880470/54660624-18dad580-4b12-11e9-9f48-fa630c44a584.png">

**Comment by gmileka** [comment]
Hi v-jiq,

We have seen similar logs when the plug-in had some missing dependencies. Is it possible that it requires some dlls and they are not at the same folder?

If that's not the case, I would recommend to temporary change the plug-in configuration from out-of-proc to in-proc. You can do that by changed the plug-in manifest file and setting the "outOfProc" to false. This should narrow down the problem - and the you can share the logs again...

Let us know how this goes...

thanks,
george

**Comment by v-jiq** [comment]
Hi george,
I have retried according to your guide , that  temporary change the plug-in configuration from out-of-proc to in-proc. 

the log prompts that failed to load library SampleComponentNamePlugin.dll. but I have putted SampleComponentNamePlugin.dll to Specified directory. The SampleComponentNamePlugin.dll are generate by refer to this link -- https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/development-scenario/developer-plugin-creation.md  and no modify anything.

below is log:
<img width="1297" alt="1553234061" src="https://user-images.githubusercontent.com/39880470/54803652-558e0480-4cab-11e9-99d9-704f4e81e978.png">

configure file:
<img width="333" alt="1553237193(1)" src="https://user-images.githubusercontent.com/39880470/54805251-59bd2080-4cb1-11e9-870b-17cd9ec020ac.png">

Thanks

**Comment by gmileka** [comment]
Hi v-jiq,

The device agent finds the dll. So, your configuration seem to be fine.

The error returned is 193 - looking this up in Windows codes, it's "is not a valid Win32 application".

Does the architecture of the dll matches the architecture of the agent/device? (x64, win32, arm, etc).

thanks,
george

**Comment by v-jiq** [comment]
Thanks george, as you said, the architecture error caused this problem!!
