### ISSUE TITLE
Azure-client-tools whether support that device send message to cloud by D2C command. 

### ISSUE THREAD

**Issue by v-jiq** [ms-iot/azure-client-tools#17]
Hi ,
so far, I know that azure-client-tools has provided two way(device twin & direct method) for client to manage device.

But now , I am Facing scene  that device send the real time of data  to cloud. I think that D2C is most Effective way for this scene. but,  I don't know that the azure-client-tools whether support that device send message to cloud by D2C command, because i not found Similar call in azure-client-tools sample and the azure-client-tools  document doesn't seem to introduce D2C .

who knows this tool  whether support D2C ?

Thanks!!

**Comment by gmileka** [comment]
Hi v-jiq,

Sending a message from a plug-in to the cloud is currently not supported. However, we are releasing an update before the end of April that will support it.

thanks,
george

**Comment by v-jiq** [comment]
Thanks george!!
