### ISSUE TITLE
Quickstart guide on Timeinfo plugin does not work

### ISSUE THREAD

**Issue by roycey** [ms-iot/azure-client-tools#29]
## Bug description
Please provide a clear and concise description of the problem.
The quick start guide for the timeInfo plugin does not work. There is an error in the reported properties of the Device Twin as shown below
"timeInfo": {

 "__meta": {

 "deploymentStatus": "failed",

 "deploymentId": "time_info_v1",

 "deviceInterfaceVersion": "",

 "time": "2019-05-07T16:34:24Z"

 },

 "__errors": {

 "timeInfo": {

 "code": -2,

 "context": "timeInfo",

 "message": "missing json value: serviceInterfaceVersion",

 "parameters": {},

 "subsystem": "deviceManagement"

 }

## Steps to reproduce
1. Follow the steps to make changes to the Desired properties of the TimeInfo plugin
2. The Reported section has the above error and the device still shows the older timestamp

## Observed behavior
Please provide a description of the observed behavior.

## Expected behavior
The plugin needs to change the timezone on the device

## Version (please provide the following information):
 - OS:
 - branch:

## Additional notes
Feel free to provide any additional notes.

**Comment by gmileka** [comment]
Thanks for finding this issue, roycey -

This is a documentation bug. The correct json should look like this:
<pre>
            "timeInfo": {
              "__meta": {
                "deploymentId": "time_info_v1",
                "serviceInterfaceVersion": "1.0.0"
              },
              "ntpServer": "time.windows.com",
              "dynamicDaylightTimeDisabled": false,
              "timeZoneKeyName": "Mountain Standard Time",
              "timeZoneBias": 420,
              "timeZoneDaylightBias": -60,
              "timeZoneDaylightDate": "0000-03-02T02:00:00",
              "timeZoneDaylightName": "Mountain Daylight Time",
              "timeZoneDaylightDayOfWeek": 0,
              "timeZoneStandardBias": 0,
              "timeZoneStandardDate": "0000-11-01T02:00:00",
              "timeZoneStandardName": "Mountain Standard Time",
              "timeZoneStandardDayOfWeek": 0
            }
</pre>

We're updating the docs shortly.

**Comment by gmileka** [comment]
Fixed the docs with commit 906df93111bb2c27e93a04c5914f53b12a522d0e.
