### ISSUE TITLE
DPS Reprovisioning to new IoT Hub and disenrollment/deprovisioning

### ISSUE THREAD

**Issue by thj-dk** [ms-iot/azure-client-tools#40]
[Reprovisioning](https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device-reprovision) and [disenrollment](https://docs.microsoft.com/en-us/azure/iot-dps/how-to-revoke-device-access-portal) through Azure Device Provisioning Service, are these features supported? From our tests, it doesn't seem like the Azure DM client is communicating with the DPS service once provisioned. Neither on reboot.

I'd like to move devices from one hub to another, either by migrating data, or resetting to initial configuration, or disabling devices altogether, from accessing the hubs.

And in case of device re-location to another customer or similar, we'd like to reset configuration, or disenroll/deprovision the device.

**Comment by gmileka** [comment]
Hi thj-dk,

Correct, today we do not support this. The current logic is that if the device has been provisioned, we do not attempt to re-provision it. We can definitely look into supporting this scenario in the future.

I'll leave this open as our team discuss what we can do.

thanks,
george

**Comment by thj-dk** [comment]
Alright. In case I need to move a device from one hub to another - how would you approach that then?With or without access to the device.

**Comment by gmileka** [comment]
The following steps would need to take place:
- Write a plug-in to clear the TPM. This would allow the DPS provisioning to be re-invoked one restart. The plug-in can be invoke as a direct method, and it can utilize limpet.exe to clear the TPM. So how the RemoteWipe is implemented for a very close example on how to do that.
- Write service-side code that will read the device twin of each device we want to move, get its desired properties, and apply them to either:
    - The enrollment of the device in DPS... At this point DPS should be pointing to the new IoT Hub.
    - The new twin directly if it's been created...
