### ISSUE TITLE
Problem installing the software TPM

### ISSUE THREAD

**Issue by gmileka** [ms-iot/azure-client-tools#43]
(originally posted by [leesiyuan](https://github.com/leesiyuan) [here](https://github.com/ms-iot/azure-client-tools/issues/39)).

Hi, I have an associate question, I also want to use TPM Provisioning in Retail Image, but I can't get the sTPM well installed.
In the Windows Device Portal, every time I try to install Software TPM Emulator, my Raspberry Pi reboot and show No TPM installed.
I also tried PowerShell command
`Limpet.exe -azuredps –enrollmentinfo`
and i got a result like:

<pre>
<?xml version="1.0" encoding="utf-8"?>
<TpmInfo>TpmNotSupported</TpmInfo>
</pre>

The TPM works fine in Test Image but even I use the same Features for the Retail image, I can’t use the TPM.
So how could I use the sTPM in a Retail image? Thanks!

**Comment by mohandatla** [comment]
Windows inbox software tpm emulator on retail images is not supported. However you can explore options 
a. Create custom UEFI binary to have ACPI entry to load the tpm emulator.
b. Use the open source network software tpm simulator created by TCG i.e. https://github.com/microsoft/ms-tpm-20-ref.
