### ISSUE TITLE
Support communicating through Edge gateway

### ISSUE THREAD

**Issue by lanatmwan** [ms-iot/azure-client-tools#46]
AFAIK, anything capable of connecting to IoTHub can also connect through an Azure Edge instance as though it were a gateway by simply modifying the connection string.
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-as-gateway

I was able to muddle my way through the documentation for DeviceAgent and connect my device directly to IoTHub. While I wouldn't say it was "no touch", it did require minimal steps to be performed on the device which was nice. Now instead of directly connecting it to IoTHub, I want to route connections through my edge gateway instance. That should only require DPS to send the Edge connection string  to my provisioned device but I don't see any way to do that.

**Comment by gmileka** [comment]
Hi lanatmwan,

This [Create transparent gateway device](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway) can help point you in the right direction.
Let us know if you have further questions...

thanks,
george
