### ISSUE TITLE
Build for arm architecture failed.

### ISSUE THREAD

**Issue by luyaok** [ms-iot/azure-client-tools#48]
## Bug description
I can build for x86 and x64 successfully. But when I run `build.cmd arm Debug 10.0.16299.0` I get the following error:

```
d:\sample\azure-client-tools\deps\azure-iot-sdk-c\c-utility\src\gbnetwork.c(14): fatal error C1083: Cannot open include
 file: 'sys/socket.h': No such file or directory [D:\Sample\azure-client-tools\deps\azure-iot-sdk-c\arm\c-utility\aziot
sharedutil.vcxproj]
```

## Steps to reproduce
I followed this document: https://github.com/ms-iot/azure-client-tools/blob/master/docs/limpet/limpet.md#set-up-limpet

## Version (please provide the following information):
 - OS: Windows 10 1903
 - branch: master

**Comment by gmileka** [comment]
I wonder if there's something wrong with the cloning... 

Do you have the following files?
deps\security\LimpetMCU\Middlewares\Third_Party\LwIP\src\include\posix\sys\socket.h
deps\security\LimpetMCU\Middlewares\Third_Party\mbed.org\Socket\Socket.h
deps\security\RazorClamMCU\Middlewares\Third_Party\LwIP\src\include\posix\sys\socket.h

**Comment by gmileka** [comment]
I'm closing as a 'no repro'. Please, re-open if you still see the issue.
