### ISSUE TITLE
Install UWP app on Windows 10 IoT Enterprise

### ISSUE THREAD

**Issue by LeonardBae** [ms-iot/azure-client-tools#49]
## Bug description
I am currently testing the Azure Device Agent on **Win10 IoT Enterprise 32bit and 64bit.**
However, if you **install the UWP app** through Device Twin, the application installs, but an error occurs when **iotstartup.exe** is executed.
And the Reported property has the following error.

"uwpApps": {
        "__errors": {
          "335344b1-60f3-46a7-927d-d992735bb566": {
            "code": -1,
            "context": "335344b1-60f3-46a7-927d-d992735bb566",
            "message": "**invalid map<K, T> key"**,
            "parameters": {},
            "subsystem": "unknown"
          }
        },
        "__meta": {
          "deploymentId": "app_install1",
          "deploymentStatus": "failed",
          "deviceInterfaceVersion": "1.0.0",
          "time": "2019-07-23T17:32:36Z"
        },
        "apps": {
          "335344b1-60f3-46a7-927d-d992735bb566_65ts46eahwtf2": {
            "pkgFamilyName": "335344b1-60f3-46a7-927d-d992735bb566_65ts46eahwtf2",
            "version": "not installed"
          }
        }
      }

Also, when I run the Device Agent in debug mode, the following **iotstartup.exe error** occurs.

09-14-10 AM [00032724] [00031596] property to find = apps
09-14-10 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::UwpAppManagementPlugin::UwpHelpers::IotStartupExePath
09-14-10 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::Utils::Process::Launch
09-14-10 AM [00032724] [00031596] Child process has been launched.
09-14-10 AM [00032724] [00031596] Child process has exited.
**09-14-10 AM [00032724] [00031596] Command return Code: -214702489409-14-10 AM [00032724] [00031596] Command output : No headed application registered**

09-14-10 AM [00032724] [00031596] property to find = startup
09-14-10 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::UwpAppManagementPlugin::UwpAppManagementHandler::FindApp
09-14-10 AM [00032724] [00031596] Finding package: 335344b1-60f3-46a7-927d-d992735bb566_65ts46eahwtf2
09-14-43 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::UwpAppManagementPlugin::UwpHelpers::UpdateAppStartup
09-14-43 AM [00032724] [00031596] Updating app startup for: 335344b1-60f3-46a7-927d-d992735bb566_65ts46eahwtf2
09-14-43 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::UwpAppManagementPlugin::UwpHelpers::IotStartupExePath
09-14-43 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::UwpAppManagementPlugin::UwpHelpers::GetAppStartupType
09-14-43 AM [00032724] [00031596] Getting app startup for: 335344b1-60f3-46a7-927d-d992735bb566_65ts46eahwtf2
09-14-43 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::UwpAppManagementPlugin::UwpHelpers::IotStartupExePath
09-14-43 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::Utils::Process::Launch
09-14-43 AM [00032724] [00031596] Child process has been launched.
09-14-43 AM [00032724] [00031596] Child process has exited.
**09-14-43 AM [00032724] [00031596] Command return Code: -214702489409-14-43 AM [00032724] [00031596] Command output : No headed application registered
09-14-43 AM [00032724] [00031596] Generic standard exception occured: invalid map<K, T> key**
09-14-43 AM [00032724] [00031596] Microsoft::Azure::DeviceManagement::Common::ReportedErrorList::AddError

Is iotstartup.exe not supported on enterprise?

## Version (please provide the following information):
 - OS: Windows 10 IoT Enterprise 1809
 - branch: master

**Comment by gmileka** [comment]
IoTStartup.exe is not supported on IoT Enterprise. It is supported only on IoT Core.

**Comment by LeonardBae** [comment]
Hello, gmileka.

However, UWP management plug-in works through iotstartup.exe and reports result to twin's reported property.
Does Device Agent fully support IoT Enterprise?

Thank you.
