### ISSUE TITLE
How to Install/Uninstall/List applications?

### ISSUE THREAD

**Issue by parbergius** [ms-iot/azure-client-tools#5]
Hi. 
There seems to be no plugin that handles application management. Is that right? Do I have to develop it myself or will it be included in the next release?

**Comment by gmileka** [comment]
Hi parbergius,

We are planning on in implementing the application management plug-in in the February/March time frame.

What other plug-ins are you looking for?

thanks,
george

**Comment by parbergius** [comment]
Hi.
Okey, thanks for that information :) 
We also need to be able to put an application as a startup. 

An nice-to-have would be a screen capture-plugin. We are now using iot-core-azure-dm-client and have implement out own screen capture functionallity. 
Thanks, Pär

**Comment by gmileka** [comment]
Hi Pär,

The ability to configure an appx to be the start-up application will be there.

I'll take the screen capture plug-in to the team to consider. Is open-sourcing the screen capture plug-in you have already built an option?

thanks,
george

**Comment by parbergius** [comment]
Okey, sounds good with the abillity to set start-up applications. 

The screen capture functionallity we built works togeheter with iot-core-azure-dm-client. Our code is not open soruce but the solution we used was to execute ScreenCapture.exe from c# and upload the result via DeviceClient to the storage account connected to out IoT Hub.

**Comment by gmileka** [comment]
Hi parbergius,

We have just updated the repo with the application functionality. Please, docs can be found [here](https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/schema/configuration-groups/uwpapplication-management.md). Let us know how this goes...

thanks,
george
