### ISSUE TITLE
Desired Configuration is Null

### ISSUE THREAD

**Issue by hasanalpzengin** [ms-iot/azure-client-tools#57]
## Bug description
Device throws

> "windowsUpdate": {
        "__meta": {
          "deploymentId": "unspecified",
          "deploymentStatus": "failed",
          "deviceInterfaceVersion": "",
          "time": "2020-01-24T16:30:27Z"
        },
        "activeHoursEnd": 23,
        "activeHoursStart": 0,
        "allowAutoUpdate": 1,
        "allowUpdateService": 0,
        "branchReadinessLevel": 16,
        "deferFeatureUpdatesPeriodInDays": 0,
        "deferQualityUpdatesPeriodInDays": 0,
        "pauseFeatureUpdates": 0,
        "pauseQualityUpdates": 0,
        "scheduledInstallDay": 5,
        "scheduledInstallTime": 0,
        "__errors": {
          "windowsUpdate": {
            "code": 1001,
            "context": "windowsUpdate",
            "message": "Desired configuration is Null",
            "parameters": {},
            "subsystem": "DeviceAgent"
          }
        }
      },
error when tried to update win 10 version.
## Steps to reproduce
add windowsUpdate key to desiredProperties:
> "windowsUpdate": {
        "__meta": {
          "deploymentId": "windows_update_v1",
          "deviceInterfaceVersion": "1.0.0",
        },
        "activeHoursEnd": 23,
        "activeHoursStart": 0,
        "allowAutoUpdate": 1,
        "allowUpdateService": 0,
        "branchReadinessLevel": 16,
        "deferFeatureUpdatesPeriodInDays": 0,
        "deferQualityUpdatesPeriodInDays": 0,
        "pauseFeatureUpdates": 0,
        "pauseQualityUpdates": 0,
        "scheduledInstallDay": 5,
        "scheduledInstallTime": 0,
        }

## Observed behavior
Error given above thrown

## Expected behavior
windows 10 version must be upgraded

## Version (please provide the following information):
 - OS:Windows 10.0.17763.615
 - branch: master

**Comment by ghost** [comment]
The Device Agent only sets the configuration for the update. Can you please confirm that the Windows Update Service is running on the device? 
sc query wuauserv

**Comment by hasanalpzengin** [comment]
I have contacted with device manifacturer and they told me update service is disabled so @roycey 's prediction can be the reason.
Thanks for help.
