### ISSUE TITLE
migration from iot-core-azure-dm-client

### ISSUE THREAD

**Issue by mburumaxwell** [ms-iot/azure-client-tools#6]
Hi,

Opening the [iot-core-azure-dm-client repository](https://github.com/ms-iot/iot-core-azure-dm-client) states that the future is in this repository. I have a few questions:

1. Is there any documentation on how to migrate to this new client tools?
2. Are the new tools in this repository backward compatible?
3. I could not find any examples for C# or dotnet. Does it mean that the client tools will only support UWP on cpp?

**Comment by gmileka** [comment]
Hi mburumaxwell,
1. We are working on a migration guide. Here is a very short version of it:
    a. The Json schema in the twin:
          i. The attributes names/meaning remain the same for the most part.
          ii. None of the configuration is under a 'windows' node anymore (saved one level of nesting).
         iii. Error reporting is using a new schema.
   b. The UWP interface
         i. This version does not depend on sharing the Azure IoT Hub connection with a UWP application.
        ii. This means that users can get rid of the code in their UWP application that connected with the nt service (i.e. SystemConfigurator).
       iii. For cases where the UWP application relied on the SystemConfigurator, we are asking for customer feedback on what these cases are and we can work with them on resolving them one by one.

2. The new schema is not backward compatible as outlined in the first bullet. However, it is very close. It should require minimal changes on the Cloud Solution/Operator application part to adopt the new schema.

3. The device management client is a standalone service whose interface is Azure IoT Hub. You can still write your Azure application on the device using your preferred language.
You might be referring to scenarios where the UWP application is invoking a device management functionality?
If so, could you please outline what that functionality is? We'd like to work with you on understanding the scenario.

Also, feel free to contact me directly at gmileka at microsoft com for quick responses.

thanks,
george

**Comment by gmileka** [comment]
Hi mburumaxwell,

We've updated the repo with a write-up on the migration [here](https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/migration-from-old-client.md).

Let us know if you have any questions...

thanks,
george
