### ISSUE TITLE
Functional Parity?

### ISSUE THREAD

**Issue by jezzsantos** [ms-iot/azure-client-tools#7]
According to: https://github.com/ms-iot/iot-core-azure-dm-client this repo is the future of the DM capability.
Have I got it right that the `device-agent` in this repo logically replaces the `dm-client`?

We have not gotten far with the `dm-client` yet, so we are considering adopting this `device-agent` instead.

However, I am not seeing any support in this `device-agent` for app update, or app install like there is in `dm-client`.

Can this `device-agent` still install a UWP app, and then upgrade the app with a new version of the app, installed from a package file in Azure Storage blob?

**Comment by gmileka** [comment]
Hi jezzsantos,

You are right - we are replacing the iot-core-azure-dm-client with this repo.

Currently, we have not ported the UWP app management support yet to the new repo/agent. 

However, we are currently working on it and it will be made available as soon as it is ready.

Feedback is welcome! 

What other functionality from the older repo are you considering? This helps us prioritize the porting order.

Is there some feature you wanted but couldn't find in either?

thanks,
george

**Comment by jezzsantos** [comment]
Thanks @gmileka ,

At this point we just need the ability to install and update an existing application of our own onto the device, and start it, and set it as the startup foreground application.

**Comment by gmileka** [comment]
Thanks jezzsantos - we should be able to share something with you for application management sometime in March.

**Comment by AlmaJensen** [comment]
Is there an update about this feature this is one I'm really looking for as well.

**Comment by mms-** [comment]
Soon or should we use the old repo? Does the old repo support UWP app update?

**Comment by gmileka** [comment]
Hello everybody,

This took us longer than we thought - but we're excited to say that it is available now.

Docs can be found [here](https://github.com/ms-iot/azure-client-tools/blob/master/docs/device-agent/schema/configuration-groups/uwpapplication-management.md).

Let us know how this goes...

I'll close this issue now... feel free to open a new issue if you see any problems.

thanks,
george

**Comment by mms-** [comment]
I am new to this, how does https://github.com/Azure/azure-iot-sdks relate to these tools? What are the use cases?
