### ISSUE TITLE
"Azure Clients" are not shown on Microsoft Edge

### ISSUE THREAD

**Issue by shijiong** [ms-iot/azure-client-tools#8]
Hello, friends

Today I try to use Azure Client Tools on Windows 10 IoT Core Build 17763.107. However, it seems that this tool cannot be shown on Microsoft Edge 44.17763.1.0. Meanwhile, it works on Google Chrome. See the picture as follows. The left part is Microsoft Edge, while the right part is Google Chrome. They connect to the same device. And the Azure Client Tools is not shown on Microsoft Edge.
![iot clients](https://user-images.githubusercontent.com/12369448/52679092-e6681680-2f6e-11e9-9a88-53532c8b3e0b.png)

**Comment by gmileka** [comment]
Thanks for reporting this, Shijiong - we'll be taking a look.

**Comment by gmileka** [comment]
This is most likely a caching issue. Could you please try clearing your internet cache from the UI? Please, feel free to re-open the issue if it still persists...

**Comment by shijiong** [comment]
Hello, @gmileka 
Thanks for your information. I confirm that this is a caching issue. After clearing the Edge cache, it works fine.
